version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: authserviceIN6VB_postgres
    restart: always
    environment: 
        POSTGRES_DB: KinalSportsIN6NV
        POSTGRES_USER: root
        POSTGRES_PASSWORD: admin
    ports:
    - "5435:5432"
    
